language: python

python:
  - "3.8"

before_install:
  - curl -fsS -o get-poetry.py https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py
  - python get-poetry.py --preview -y
  - source $HOME/.poetry/env

install:
  - poetry install

script:
  - poetry run pytest -q tests